Backup failed for Site xyz.com. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 843, in backup
    odb = scheduled_backup(
      context = {'sites': ['xyz.com'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x7f55a89018a0>
      exit_code = 0
      rollback_callback = None
      site = 'xyz.com'
  File "apps/frappe/frappe/utils/backups.py", line 568, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f55a78108e0>
  File "apps/frappe/frappe/utils/backups.py", line 605, in new_backup
    odb = BackupGenerator(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f55a78108e0>
  File "apps/frappe/frappe/utils/backups.py", line 89, in __init__
    self.setup_backup_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f55a7810980>
      db_name = '_10095d3054764b4c'
      user = '_10095d3054764b4c'
      password = ********
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      db_socket = None
      db_host = '127.0.0.1'
      db_port = '3306'
      db_type = 'mariadb'
      backup_path_conf = None
      ignore_conf = False
      compress_files = False
      include_doctypes = ''
      exclude_doctypes = ''
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x7f55a78108e0>
      site = 'xyz.com'
  File "apps/frappe/frappe/utils/backups.py", line 121, in setup_backup_tables
    existing_tables = frappe.db.get_tables()
      self = <frappe.utils.backups.BackupGenerator object at 0x7f55a7810980>
  File "apps/frappe/frappe/database/mariadb/database.py", line 484, in get_tables
    .run(pluck=True)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f55a78a94c0>
      cached = True
      to_query = True
      tables = None
      information_schema = <pypika.queries.Schema object at 0x7f55a7810ad0>
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      args = ()
      kwargs = {'pluck': True}
      child_queries = []
      params = {'param1': '_10095d3054764b4c'}
      execute_child_queries = <function patch_query_execute.<locals>.execute_child_queries at 0x7f55a77d9580>
      prepare_query = <function patch_query_execute.<locals>.prepare_query at 0x7f55a77d9620>
  File "apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f55a78a94c0>
      query = 'SELECT `table_name` FROM `information_schema`.`tables` WHERE `table_schema`=%(param1)s'
      values = {'param1': '_10095d3054764b4c'}
      as_dict = 0
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = True
      as_iterator = False
  File "apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f55a78a94c0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f55a78a94c0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f55a78a94c0>
  File "apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7f55a78a94c0>
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
      self = <pymysql.connections.Connection object at 0x7f55a7a4de20>
      user = '_10095d3054764b4c'
      password = ********
      host = '127.0.0.1'
      database = '_10095d3054764b4c'
      unix_socket = None
      port = 3306
      charset = 'utf8mb4'
      collation = 'utf8mb4_unicode_ci'
      sql_mode = None
      read_default_file = None
      conv = {<class 'bool'>: <function escape_bool at 0x7f55a78f91c0>, <class 'int'>: <function escape_int at 0x7f55a78f9260>, <class 'float'>: <function escape_float at 0x7f55a78f9300>, <class 'str'>: <function escape_str at 0x7f55a78f9580>, <class 'bytes'>: <function escape_bytes at 0x7f55a78f94e0>, <class 'tuple'>: <function escape_sequence at 0x7f55a78f9080>, <class 'list'>: <function escape_sequence at 0x7f55a78f9080>, <class 'set'>: <function escape_sequence at 0x7f55a78f9080>, <class 'frozenset'>: <function escape_sequence at 0x7f55a78f9080>, <class 'dict'>: <function escape_dict at 0x7f55a78f8fe0>, <class 'NoneType'>: <function escape_None at 0x7f55a78f9620>, <class 'datetime.date'>: <function escape_date at 0x7f55a78f98a0>, <class 'datetime.datetime'>: <function escape_datetime at 0x7f55a78f9800>, <class 'datetime.timedelta'>: <function escape_timedelta at 0x7f55a78f96c0>, <class 'datetime.time'>: <function escape_time at 0x7f55a78f9760>, <class 'time.struct_time'>: <function escape_struc...
      use_unicode = True
      client_flag = 3842573
      cursorclass = <class 'pymysql.cursors.Cursor'>
      init_command = None
      connect_timeout = 10
      read_default_group = None
      autocommit = False
      local_infile = False
      max_allowed_packet = 16777216
      defer_connect = False
      auth_plugin_map = None
      read_timeout = None
      write_timeout = None
      bind_address = None
      binary_prefix = False
      program_name = None
      server_public_key = ********
      ssl = None
      ssl_ca = None
      ssl_cert = None
      ssl_disabled = None
      ssl_key = ********
      ssl_key_password = ********
      ssl_verify_cert = None
      ssl_verify_identity = None
      compress = None
      named_pipe = None
      passwd = ********
      db = None
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
      self = <pymysql.connections.Connection object at 0x7f55a7a4de20>
      sock = <socket.socket [closed] fd=-1, family=2, type=1, proto=6>
      kwargs = {}
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
      self = <pymysql.connections.Connection object at 0x7f55a7a4de20>
      charset_id = 45
      data_init = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
      data = b'\r\xa2:\x00\xff\xff\xff\x00-\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00_10095d3054764b4c\x00\x14\xa7\xe6\x8d-9PR\\K3\xc5{|\xa1\xb9N\xec\x01\xc7\xcf_10095d3054764b4c\x00mysql_native_password\x007\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x06219924'
      authresp = b'\xa7\xe6\x8d-9PR\\K3\xc5{|\xa1\xb9N\xec\x01\xc7\xcf'
      plugin_name = b'mysql_native_password'
      connect_attrs = b'\x0c_client_name\x07pymysql\x0f_client_version\x051.1.1\x04_pid\x06219924'
      k = b'_pid'
      v = b'219924'
  File "env/lib/python3.12/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7f55a7a4de20>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\xa2\x06#28000Access denied for user \'_10095d3054764b4c\'@\'localhost\'")
      packet_header = b'?\x00\x00\x02'
      btrl = 63
      btrh = 0
      packet_number = 2
      bytes_to_read = 63
      recv_data = b"\xff\xa2\x06#28000Access denied for user '_10095d3054764b4c'@'localhost'"
      packet = <pymysql.protocol.MysqlPacket object at 0x7f55a7810bb0>
  File "env/lib/python3.12/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7f55a7810bb0>
      errno = 1698
  File "env/lib/python3.12/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\xa2\x06#28000Access denied for user '_10095d3054764b4c'@'localhost'"
      errno = 1698
      errval = "Access denied for user '_10095d3054764b4c'@'localhost'"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1698, "Access denied for user '_10095d3054764b4c'@'localhost'")
set -o pipefail; /usr/bin/mariadb-dump --user=_06243711d933417b --host=127.0.0.1 --port=3306 --password=********** --single-transaction --quick --lock-tables=false _06243711d933417b | /usr/bin/gzip >> ./hardik.com/private/backups/20250716_153002-hardik_com-database.sql.gz

Backup Summary for hardik.com at 2025-07-16 15:30:08.985387
Config  : ./hardik.com/private/backups/20250716_153002-hardik_com-site_config_backup.json 94.0B
Database: ./hardik.com/private/backups/20250716_153002-hardik_com-database.sql.gz         265.0KiB
Backup for Site hardik.com has been successfully completed
set -o pipefail; /usr/bin/mariadb-dump --user=_06243711d933417b --host=127.0.0.1 --port=3306 --password=********** --single-transaction --quick --lock-tables=false _06243711d933417b | /usr/bin/gzip >> ./hardik.com/private/backups/20250716_213002-hardik_com-database.sql.gz

Backup Summary for hardik.com at 2025-07-16 21:30:03.030485
Config  : ./hardik.com/private/backups/20250716_213002-hardik_com-site_config_backup.json 94.0B
Database: ./hardik.com/private/backups/20250716_213002-hardik_com-database.sql.gz         274.2KiB
Backup for Site hardik.com has been successfully completed
set -o pipefail; /usr/bin/mariadb-dump --user=_06243711d933417b --host=127.0.0.1 --port=3306 --password=********** --single-transaction --quick --lock-tables=false _06243711d933417b | /usr/bin/gzip >> ./hardik.com/private/backups/20250717_152959-hardik_com-database.sql.gz

Backup Summary for hardik.com at 2025-07-17 15:30:02.125102
Config  : ./hardik.com/private/backups/20250717_152959-hardik_com-site_config_backup.json 94.0B
Database: ./hardik.com/private/backups/20250717_152959-hardik_com-database.sql.gz         292.8KiB
Backup for Site hardik.com has been successfully completed
set -o pipefail; /usr/bin/mariadb-dump --user=_06243711d933417b --host=127.0.0.1 --port=3306 --password=********** --single-transaction --quick --lock-tables=false _06243711d933417b | /usr/bin/gzip >> ./hardik.com/private/backups/20250718_153006-hardik_com-database.sql.gz

Backup Summary for hardik.com at 2025-07-18 15:30:11.796962
Config  : ./hardik.com/private/backups/20250718_153006-hardik_com-site_config_backup.json 94.0B
Database: ./hardik.com/private/backups/20250718_153006-hardik_com-database.sql.gz         313.3KiB
Backup for Site hardik.com has been successfully completed
set -o pipefail; /usr/bin/mariadb-dump --user=_06243711d933417b --host=127.0.0.1 --port=3306 --password=********** --single-transaction --quick --lock-tables=false _06243711d933417b | /usr/bin/gzip >> ./hardik.com/private/backups/20250718_153102-hardik_com-database.sql.gz

Backup Summary for hardik.com at 2025-07-18 15:31:05.545507
Config  : ./hardik.com/private/backups/20250718_153102-hardik_com-site_config_backup.json 94.0B
Database: ./hardik.com/private/backups/20250718_153102-hardik_com-database.sql.gz         313.5KiB
Backup for Site hardik.com has been successfully completed
